### PR TITLE
Creates FunctionOperator, a useful wrapper for operators defined by generic functions

### PR DESCRIPTION
**Pull request by cako**
Create LinearOperators quickly by calling:

    FunctionOperator(f, n)
    FunctionOperator(f, nr, nc)
    FunctionOperator(f, fc, nc)

or

    FunctionOperator(f, fc, nr, nc)

### CODE REVIEW

**Comment by mrava87** [comment]
Nice :) how does this compare to the actual scipy one which has the option to pass functions instead of subclassing, see in examples in this page https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.LinearOperator.html?

I guess your one gets all the extra bit of our linear operator (doc, eigs...)?

**Comment by cako** [comment]
1. 

> Nice :) how does this compare to the actual scipy one which has the option to pass functions instead of subclassing, see in examples in this page https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.LinearOperator.html?
> 
> I guess your one gets all the extra bit of our linear operator (doc, eigs...)?

Pretty much just has the extra bits. The functionality of the class could also be simply implemented as a utility function (all the hard work is done in `__init__`), but it was a good exercise to try and implement this! I still haven't decided whether I should call `super()super().__init__` inside my class (thereby initializing `scipy.sparse.linalg.LinearOperator` in order to validate `shape` and `dtype` but at the moment I am leaning against this.


> I guess you fixed to code but not the comment was ok before, with ‘overdetermined’?

Yup, you are right, I'll change it.

**Comment by mrava87** [comment]
Sounds good :) I think this is useful to have especially as it is like the scipy one (and agree about leaving super.super out for the moment)

We can add it in the documentation next to LinearOperator as it is very generic, can be used for anything, agree? But I would suggest that in the docstring or somewhere we explain that this can be used for very simple operators where forward and adjoint are for example lambda function.  Things like this 

G = np.matrix(np.random.normal(0, 1, (par['nr'], par['nc'])) +
                  np.random.normal(0, 1, (par['nr'], par['nc']))*par['imag'],
                  dtype=par['dtype'])

     def forward_f(x):
        return G @ x
    def adjoint_f(y):
        return G.H @ y
can actually be very nasty to debug because all of a sudden you have things outside of the operator modifying the operator, which is why I found the subclassing part nicer than passing functions directly. I just want to ensure that none develops an operator not using subclassing... what do you think?

Btw, I am going to change LinearOperator into _LinearOperator soon as this is not effectively for users, you can only use it as parent class and not call it directly, makes sense?

**Comment by cako** [comment]
> But I would suggest that in the docstring or somewhere we explain that this can be used for very simple operators where forward and adjoint are for example lambda function.

Yes, lambda functions are very good for this case, but also not great at debugging. That's why I decided to go with a `def` in this case. Now that the code works, we can revert to lambda :stuck_out_tongue_winking_eye: 

> all of a sudden you have things outside of the operator (G) which if you modify you also are modifying the operator behavior (?)

True, I had not thought of this. Overall I would argue it can be very practical, especially for cases where your linear function depends on other arguments, so you can do `FunctionOperator(lambda x: f(x, arg1, arg2).flatten(), n)` for example. I think I will add something in the documentation to this effect.

> Btw, I am going to change LinearOperator into _LinearOperator soon as this is not effectively for users, you can only use it as parent class and not call it directly, makes sense?

Julia library [LinearMaps](https://github.com/Jutho/LinearMaps.jl) makes a call to `LinearMaps` (equivalent to `LinearOperator`) actually be a call to `FunctionMap`. I don't really like this approach because it masks what is going on and you have do dig deep sometimes to find who initializes what. On the other hand, I am not sure `_LinearOperator` should be "hidden", the scipy one isn't, for example. Maybe renaming to `PyLinearOperator` could avoid confusion. I think it is really up to the documentation to let people know that they don't have to create their linear operators from scratch (aka, subclass LinearOperator), and can use the ready-made ones.

**Comment by mrava87** [comment]
Just a stupid question, if you have ``FunctionOperator(f, n)`` can we not just assume fc=f, otherwise why would you allow a user to call this if we just return an error?

For ``FunctionOperator(f, n, m)`` instead I would say that if m!=n then self-adjoint doesn't make sense so we raise an error but if n==m again we can force fc=f?

**Comment by mrava87** [comment]
Final question, any reason for having a main in ``test_functionoperator`` file. ``pytest`` compared to ``unittest`` does not require mains running the classes, unless you have a reason for this I suggest we remove it :)

**Comment by cako** [comment]
> Just a stupid question, if you have `FunctionOperator(f, n)` can we not just assume fc=f, otherwise why would you allow a user to call this if we just return an error?
> 
> For `FunctionOperator(f, n, m)` instead I would say that if m!=n then self-adjoint doesn't make sense so we raise an error but if n==m again we can force fc=f?

My first iteration of the function did exactly that. But hard-coding this means that whenever methods find `_rmatmul`, they will be tempted to use it, implicitly assuming that the operator is symmetric. Instead, I think better behavior is to simply say: the user has not coded this, this method cannot be used. "Explicit is better than implicit" :stuck_out_tongue:

**Comment by cako** [comment]
> Final question, any reason for having a main in `test_functionoperator` file. `pytest` compared to `unittest` does not require mains running the classes, unless you have a reason for this I suggest we remove it :)

I thought I had gotten rid of this! It is pretty useful for running only those specific tests with:

    python test_functionoperator.py

I am sure pytests has a better way to do it–I just don't know it!

**Comment by mrava87** [comment]
Ahhaah no worries, I can get rid of it :)

``pytest pytests/test_functionoperator.py`` does the trick

**Comment by cako** [comment]
> > Just a stupid question, if you have `FunctionOperator(f, n)` can we not just assume fc=f, otherwise why would you allow a user to call this if we just return an error?
> > For `FunctionOperator(f, n, m)` instead I would say that if m!=n then self-adjoint doesn't make sense so we raise an error but if n==m again we can force fc=f?
> 
> My first iteration of the function did exactly that. But hard-coding this means that whenever methods find `_rmatmul`, they will be tempted to use it, implicitly assuming that the operator is symmetric. Instead, I think better behavior is to simply say: the user has not coded this, this method cannot be used. "Explicit is better than implicit"

Btw, although I haven't tested this in Python, ARPACK `eigs` should still work (at least with the LM option), as well as several other Krylov-based methods (e.g. CG)

**Comment by mrava87** [comment]
> > Just a stupid question, if you have `FunctionOperator(f, n)` can we not just assume fc=f, otherwise why would you allow a user to call this if we just return an error?
> > For `FunctionOperator(f, n, m)` instead I would say that if m!=n then self-adjoint doesn't make sense so we raise an error but if n==m again we can force fc=f?
> 
> My first iteration of the function did exactly that. But hard-coding this means that whenever methods find `_rmatmul`, they will be tempted to use it, implicitly assuming that the operator is symmetric. Instead, I think better behavior is to simply say: the user has not coded this, this method cannot be used. "Explicit is better than implicit" 😛

Agree. So in docstring shall we just tell the user that they can run:

``FunctionOperator(f, fc, n)`` for symmetric operators
``FunctionOperator(f, fc, n, m)`` for rectangular operators

**Comment by cako** [comment]
The possible calls are like this:
 
    FunctionOperator(f, n) – square operators with an unknown transpose
    FunctionOperator(f, nr, nc) – rectangular operators with an unknown transpose
    FunctionOperator(f, fc, n) – square operators with a known transpose
    FunctionOperator(f, fc, nr, nc) – rectangular operators with a known transpose

The last call is the "ideal" call. Oh, and all calls can also take `dtype`. If not provided, `float64` is used.

**Comment by mrava87** [comment]
What I mean is last and third work (or at least every call can break at runtime if the method is not consistent with nr and nc...) but the first two we basically know already that they won't work... so why even suggesting them to the user, or am I missing something?

**Comment by cako** [comment]
Basically if you don't know the adjoint (or don't care about it), you can use the first two. It's not the most common thing, but thinking practically, it seems very restrictive to require users to know adjoints all the time. Sure, they are limited in using methods which don't require the adjoint, but there are more than a few of these. The idea of throwing the error is that calls to the adjoint are not passed silently, rather, they alert the user. I was even thinking of creating a specific error (subclassed from NotImplementedError) just for adjoints.

**Comment by mrava87** [comment]
Ok I get it now. I always think that ultimately you want to solve an inverse problem and every solver requires forward and adjoint (of course this is same if self-adjoint but you need both anyways). But I agree, no harm to keep the first two if you just want to use FunctionOperator to apply an operator :)

**Pull request merged**
